CREATE TABLE IF NOT EXISTS `santi` (
  `giorno` tinyint(4) NOT NULL DEFAULT '0',
  `mese` tinyint(4) NOT NULL DEFAULT '0',
  `santi` varchar(250) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `santi` (`giorno`, `mese`, `santi`) VALUES
(1, 1, 'Maria Madre di Dio'),
(1, 2, 'Brigida, Veridiana, Brigida'),
(1, 3, 'Albino, Alba, Ugo, Ermes, Ermete'),
(1, 4, 'Dora, Irene, Ugo, Doriana'),
(1, 5, 'Brunella, Giuseppe'),
(1, 6, 'Giustino, Lia, Graziano, Lia'),
(1, 7, 'Ester, Carolina'),
(1, 8, 'Alfonso'),
(1, 9, 'Egidio, Giosuè'),
(1, 10, 'Teresa, Ariel, Ariele, Remigio'),
(1, 11, 'Tutti i Santi'),
(1, 12, 'Eligio, Natalia, Natalina, Mariano'),
(2, 1, 'Basilio, Evelina, Modesto'),
(2, 2, 'Maurizio, Sabatina, Sabatino'),
(2, 3, 'Simplicio, Ava, Ave, Basileo, Ulderico, Uldegigo, Ulrico'),
(2, 4, 'Isotta, Emilia, Myriam, Selene, Ginevra, Grazia, Graziella, Selenio, Regina,'),
(2, 5, 'Flaminia, Zoe, Atanasio, Flaminio, Celeste'),
(2, 6, 'Emilia, Erasmo, Elmo, Floriana, Floriano, Fosco, Fosca'),
(2, 7, 'Ottone, Ottorino'),
(2, 8, 'Eusebio'),
(2, 9, 'Ingrid, Elpidio, Ottaviano, Ottaviana'),
(2, 10, 'Angeli Custodi'),
(2, 11, 'Tobia'),
(2, 12, 'Bibiana, Viviana, Vivianna, Vivien, Evelina, Ada'),
(3, 1, 'Genoveffa'),
(3, 2, 'Ofelia, Oscar,'),
(3, 3, 'Cunegonda, Viola, Tiziana, Tiziano'),
(3, 4, 'Riccardo, Sisto,'),
(3, 5, 'Alessandro, Filippo, Giacomo, Viola'),
(3, 6, 'Clotilde, Carlo, Olivia, Oliva, Uliva, Olivana, Oliviana, Oliviera, Olivera, Viera, Wiera, Ovidio'),
(3, 7, 'Tommaso, Leone'),
(3, 8, 'Lidia'),
(3, 9, 'Gregorio, Clelia'),
(3, 10, 'Teresa'),
(3, 11, 'Silvia, Silvio, Giusto, Giustina'),
(3, 12, 'Ilaria, Saverio'),
(4, 1, 'Fausta, Angela, Elsa, Cristiana, Quintiliano, Quintiliana, Ermes, Ermete'),
(4, 2, 'Giliberto, Biagio'),
(4, 3, 'Quaresima, Andey, Casimiro, Umberto, Urbano, Nestore, Lucio'),
(4, 4, 'Isabelle, Isidora, Isidoro'),
(4, 5, 'Ada, Floriano, Silvano, Tiziano, Porfirio'),
(4, 6, 'Isabella, Quirina, Quirino, Querino, Querina'),
(4, 7, 'Cristina, Elisabetta'),
(4, 8, 'Giovanni Serenella, Ia, Iana'),
(4, 9, 'Rosalia, Rosa, Mosè'),
(4, 10, 'Francesco, Francesca, Berenice, Nice, Petronio, Petronia'),
(4, 11, 'Carlo, Rosalia, Carla, Carlotta'),
(4, 12, 'Ada, Barbara, Giovanni, Isa'),
(5, 1, 'Nazario, Amelia'),
(5, 2, 'Agata'),
(5, 3, 'Foca, Adriano, Virgilio'),
(5, 4, 'Eva, Vincenzo, Geraldo, Vincenza, Cenzo, Cenza'),
(5, 5, 'Angelo, Penelope, Tosca, Teodoro, Pellegrino, Lea, Leo, Pio, Pia'),
(5, 6, 'Bonifacio, Ferdinando, Ferdinanda, Igor, Volfango'),
(5, 7, 'Antonio, Filomena, Mena'),
(5, 8, 'Nives, Nieves, Nieve, Neves, Neve, Nevi, Neva, Osvaldo, Osvalda, Paride'),
(5, 9, 'Giordano, Vittorino'),
(5, 10, 'Tullia, Tulliana, Felicia, Felicita, Leandro, Leandra'),
(5, 11, 'Zaccaria'),
(5, 12, 'Giulio'),
(6, 1, 'Raffaella, Melchiorre, Baldassarre, Gaspare, Raffaello, Rafaelo, Rafaela'),
(6, 2, 'Amanda, Dorotea, Amando, Gastone, Guarino, Guerrino'),
(6, 3, 'Marziano, Colette, Ezio, Marziana, Marzio, Marzia'),
(6, 4, 'Celestina, Diogene, Filarete'),
(6, 5, 'Giuditta, Violante'),
(6, 6, 'Norberto, Paola, Paula, Paulina, Paoletta'),
(6, 7, 'Maria Goretti, Romola, Romolina'),
(6, 8, 'Trasfigurazione N.S. Gesù'),
(6, 9, 'Petronio, Umberto, Umberta, Eva'),
(6, 10, 'Alberta, Bruno'),
(6, 11, 'Leonardo'),
(6, 12, 'Angelica, Nicola, Dionisia, Nicoletta, Nicolina, Lina, Nicolino, Lino, Nicolò, Niccolò'),
(7, 1, 'Luciano, Luciana'),
(7, 2, 'Eugenia'),
(7, 3, 'Felicia, Augusta, Perpetua, Ermanno'),
(7, 4, 'Giovanni Battista, Cristiano, Cristiana'),
(7, 5, 'Flavio, Fulvia, Augusto, Gisella, Virginia, Stanislao, Villano, Fulvio, Augusta'),
(7, 6, 'Sabiniano, Geremia, Landolfo'),
(7, 7, 'Claudio, Apollonio, Edda, Claudia'),
(7, 8, 'Gaetano, Mafalda, Donato, Donata'),
(7, 9, 'Regina, Guido'),
(7, 10, 'Rosaria, Rosario'),
(7, 11, 'Carina, Ernesto'),
(7, 12, 'Ambrogio'),
(8, 1, 'Severino'),
(8, 2, 'Giacomina, Jacqueline, Onorato'),
(8, 3, 'Giovanni (di Dio), Salvatore'),
(8, 4, 'Dionigi'),
(8, 5, 'Vittore, Geronzio, Egle'),
(8, 6, 'Medardo'),
(8, 7, 'Elisabetta, Priscilla, Edgardo, Edgarda'),
(8, 8, 'Domenico, Emiliano'),
(8, 9, 'Bellina, Maria, Novella, Novellina'),
(8, 10, 'Porzia, Porsia, Taide, Thais, Taisia, Brigida, Ivan, Ivano, Ivana'),
(8, 11, 'Goffredo'),
(8, 12, 'Immacolata, Concetta, Lorenza, Renza, Laurenzia'),
(9, 1, 'Giuliano, Alessia, Alice'),
(9, 2, 'Apollonia'),
(9, 3, 'Francesca'),
(9, 4, 'Hilda, Tancredi'),
(9, 5, 'Gregorio, Luminosa'),
(9, 6, 'Efrem, Primo'),
(9, 7, 'Clelia, Bianca, Veronica,'),
(9, 8, 'Romano Livio, Livia'),
(9, 9, 'Sergio'),
(9, 10, 'Sara, Lorenzo, Lorenza, Loris, Renzo, Renza'),
(9, 11, 'Oreste, Fausto, Fausta, Faustina'),
(9, 12, 'Sirio, Cesare'),
(10, 1, 'Aldo, Domiziano, Domiziana'),
(10, 2, 'Guglielmo, Wilma, Scolastica, Wilma'),
(10, 3, 'Maria Eugenia, Gaio, Simplicio, Emiliano, Gaia, Caio'),
(10, 4, 'Terenzio'),
(10, 5, 'Alfio, Miro, Quarto'),
(10, 6, 'Diana, Greta, Asterio'),
(10, 7, 'Rufina, Seconda'),
(10, 8, 'Lorenzo, Lorenza, Renzo, Renza'),
(10, 9, 'Candida, Pulcheria'),
(10, 10, 'Daniele'),
(10, 11, 'Fiorenza, Leone, Fiorenzo'),
(10, 12, 'Loredana, Nazzareno, Lorena, Loretta'),
(11, 1, 'Igino'),
(11, 2, 'Eloisia, Dante, Durante'),
(11, 3, 'Costantino'),
(11, 4, 'Stanislao, Gemma, Isacco'),
(11, 5, 'Stella, Achille, Fabio, Fiorenzo, Fiorenza'),
(11, 6, 'Barnaba, Paola Frassinetti, Amabile'),
(11, 7, 'Benedetto, Olga, Emanuele, Manuel, Fabrizia, Fabrizio'),
(11, 8, 'Chiara, Susanna, Lelia'),
(11, 9, 'Diomede'),
(11, 10, 'Firminio, Emanuela, Emiliano, Bruno, Bruna, Brunella'),
(11, 11, 'Martino'),
(11, 12, 'Damaso'),
(12, 1, 'Probo, Tatiana'),
(12, 2, 'Eulalia, Alessio'),
(12, 3, 'Massimiliano, Zeno, Zenona'),
(12, 4, 'Zenone, Giulio'),
(12, 5, 'Nereo, Pancrazio, Imelde, Domitilla'),
(12, 6, 'Basilide, Onofrio'),
(12, 7, 'Fortunato'),
(12, 8, 'Macario, Giuliano, Chiara, Clara, Clarissa, Claretta'),
(12, 9, 'Maria, Marietta, Mariella, Myriam, Mara'),
(12, 10, 'Pilar, Serafino, Serafina'),
(12, 11, 'Renato, Renata, Diego, Cristiano'),
(12, 12, 'Giovanna, Rosalinda, Noemi'),
(13, 1, 'Ilaria, Ilario, Yvette, Eliana, Vero'),
(13, 2, 'Esmeralda, Fosca, Maura'),
(13, 3, 'Rodrigo, Eufrasia, Letizia'),
(13, 4, 'Martino, Ermenegildo'),
(13, 5, 'Emma, Roberto'),
(13, 6, 'Alice, Antonio'),
(13, 7, 'Enrico, Enrica'),
(13, 8, 'Ippolito, Ponziano'),
(13, 9, 'Giovanni'),
(13, 10, 'Edoardo Remo'),
(13, 11, 'Diego'),
(13, 12, 'Lucia, Odilia, Oreste, Orestilla'),
(14, 1, 'Macrina, Benedetta, Morena, Moreno, Ilaria, Ilario, Felice'),
(14, 2, 'Valentino, Valentina'),
(14, 3, 'Matilde, Valeriano, Valeriana'),
(14, 4, 'Abbondio, Ignazio, Ignazia, Lamberto'),
(14, 5, 'Corinna, Gemma, Mattia, Mattia, Bonifacio'),
(14, 6, 'Eliseo, Valeria, Valerio'),
(14, 7, 'Camillo, camilla'),
(14, 8, 'Alfredo'),
(14, 9, 'Crescenzio'),
(14, 10, 'Guendalina, Guendalino, Fortunato, Fortunata, Orlando'),
(14, 11, 'Alberico, Emiliano'),
(14, 12, 'Noemi, Giovanni (della Croce), Pompeo'),
(15, 1, 'Mauro, Maura, Ida'),
(15, 2, 'Giorgia, Sigfrido'),
(15, 3, 'Cesare, Luisa, Silvia, Lucrezia'),
(15, 4, 'Annibale, Anastasio, Anastasia'),
(15, 5, 'Germana, Torquato, Torquato'),
(15, 6, 'Germana, Enrica, Germano, Everardo, Vito'),
(15, 7, 'Bonaventura, vladimiro, Vladimira, Giacobbe'),
(15, 8, 'Assunta, Tarcisio, Tarcisia'),
(15, 9, 'Dolores, Addolorata, Emiliano'),
(15, 10, 'Teresa, Ruggero'),
(15, 11, 'Alberto'),
(15, 12, 'Valeriano, Nino'),
(16, 1, 'Marcello, Marcella'),
(16, 2, 'Giuliana'),
(16, 3, 'Eriberto, Taziano, Taziana'),
(16, 4, 'Bernadette, Grazia, Giuditta'),
(16, 5, 'Margherita, Ubaldo, Tiziano, Oderzo, Adamo'),
(16, 6, 'Giuditta, Aureliano, Aureliana, Ferruccio'),
(16, 7, 'Carmela, Elvira, Carmen'),
(16, 8, 'Stefano, Ruth, Serena, Gioacchino, Rocco, Sereno'),
(16, 9, 'Edith, Comelio, Cipriano, Edoardo, Edoarda, Editta'),
(16, 10, 'Edvige'),
(16, 11, 'Margherita, Geltrude, Edmondo, Edmonda'),
(16, 12, 'Adelaide, Albina'),
(17, 1, 'Antonio, Alba, Iole, Nadia, Nada, Iolanda, Jole, Iole, Jolanda, Anteo, Antea'),
(17, 2, 'Marianna, Patrizia,'),
(17, 3, 'Patrizio, Patrizia, Teodora, Teodoro, Wanda, Vanda'),
(17, 4, 'Arcangelo, Aniceto, Rodolfo'),
(17, 5, 'Pasquale'),
(17, 6, 'Ranieri, Manuele, Manuela'),
(17, 7, 'Alessio, Tiziana, Tiziano, Alessia'),
(17, 8, 'Carla, Giacinto, Carlo, Carlotta, Carola, Karol, Giacinta'),
(17, 9, 'Roberto, Roberta, Socrate'),
(17, 10, 'Marisa, Marisella, Marisetta, Edda, Edvige, Macario'),
(17, 11, 'Elisabetta, Eulalio, Eulalia, Eugenio, Eugenia, elda'),
(17, 12, 'Olimpia, Lazzaro'),
(18, 1, 'Prisca, Priscilla, Leonardo, Beatrice'),
(18, 2, 'Cinzia, Claudio'),
(18, 3, 'Cirillo'),
(18, 4, 'Galdino'),
(18, 5, 'Erico, Giovanni, Veneziano, Venanzia, Venanzio, Luciano, Luciana, Enrico, Enrica'),
(18, 6, 'Marina, Marinella, Marinetta, Marina'),
(18, 7, 'Calogero, Federico, Federica'),
(18, 8, 'Elena, Lauro, Tatiana'),
(18, 9, 'Arianna, Sofia, Stefania'),
(18, 10, 'Luca'),
(18, 11, 'Alda, Oddone, Noè'),
(18, 12, 'Graziano, Quinto'),
(19, 1, 'Mario, Pia, Pio'),
(19, 2, 'Corrado, Tullio, Tullo, Publio'),
(19, 3, 'Giuseppe, Giuseppina, Pino, Pina, Sibilla, Quartilla'),
(19, 4, 'Ermogene, Espedito, Emma'),
(19, 5, 'Ivo, Ivonne, Ivette'),
(19, 6, 'Romualdo'),
(19, 7, 'Federico, Simmaco, Vincenzo, Vincenza, Cenzo, Cenza'),
(19, 8, 'Giovanni, italo, Itala'),
(19, 9, 'Costanza, Gennaro, Elio, Pomposa, Costanzo'),
(19, 10, 'Isacco, Laura, Lara'),
(19, 11, 'Ponziano, Fausto'),
(19, 12, 'Fausta, Dario'),
(20, 1, 'Sebastiano, Fabiano, Teodorico'),
(20, 2, 'Ulrico, Eros'),
(20, 3, 'Claudia, Alessandra'),
(20, 4, 'Adalgisa, Odette'),
(20, 5, 'Bernardino, Anastasio, Anastasia'),
(20, 6, 'Consolata, Ettore, Novato'),
(20, 7, 'Elia, Severa, Severina, Severiana'),
(20, 8, 'Bernardo, Filiberto, Filiberta, Samuele, Samuela'),
(20, 9, 'Eustachio'),
(20, 10, 'Aurora'),
(20, 11, 'Edmondo, Ottavio, Ottavia'),
(20, 12, 'Liberato, Macario'),
(21, 1, 'Agnese, Ines'),
(21, 2, 'Eleonora, Nora, Pier Damiani, Leopoldo'),
(21, 3, 'Filemone, Benedetta, Benedetto'),
(21, 4, 'Anselmo, Corrado'),
(21, 5, 'Vittorio, Vittoria, Giulia, Angelo, Angela'),
(21, 6, 'Luigi, Marzia, Marzina, Marzialina, Marziana, Luigia, Luisa, Raul'),
(21, 7, 'Cesira, Lorenzo, Daniele,'),
(21, 8, 'Chantal, Pio, Fabrizio, Fabrizia, Natale'),
(21, 9, 'Matteo, Mattea'),
(21, 10, 'Clementina, Orsola, Letizia, Orsolina, Lina, Silvestro,'),
(21, 11, 'Presentazione Beata Vergine'),
(21, 12, 'Pietro'),
(22, 1, 'Vincenzo, Vincenza, Linda, Esmeralda, Domenico, Teodolinda, Smeralda'),
(22, 2, 'Isabella, Greta, Margherita'),
(22, 3, 'Benvenuto, Caterina, Lavinia, Lea, Nilde, Nilda, Muzio, Onofrio'),
(22, 4, 'Sotero, Caio, Leonida'),
(22, 5, 'Giulia, Rita da Cascia, Valente'),
(22, 6, 'Paolino, Flavia, Flavio'),
(22, 7, 'Maria Maddalena, Elia, Lena'),
(22, 8, 'Maria Regina, Ippolito, Ippolita'),
(22, 9, 'Maurizio, Maurizia, Tazio, Silvano'),
(22, 10, 'Donato, Salomè, Apollo'),
(22, 11, 'Cecilia'),
(22, 12, 'Francesca, Demetrio'),
(23, 1, 'Emerenziana, Ramona, Armando'),
(23, 2, 'Livio, Livia, Romana, Tea, Teo, Serena, Sereno, Romina'),
(23, 3, 'Turibio, Fedele, Nora, Norina'),
(23, 4, 'Giorgio'),
(23, 5, 'Desiderio'),
(23, 6, 'Lanfranco, Alice'),
(23, 7, 'Brigida, Rowena'),
(23, 8, 'Rosa, Rosetta, Rosella, Benito'),
(23, 9, 'Rebecca, Tecla, Vittoria, Lino, Libera, Libero, Liberino, Liberina, Libertà'),
(23, 10, 'Giovanni'),
(23, 11, 'Felicia, Clemente, Lucrezia, Felicita, Clementina'),
(23, 12, 'Giovanni'),
(24, 1, 'Francesco, Vera, Feliciano, Feliciana'),
(24, 2, 'Edilberto'),
(24, 3, 'Gabriele, Attilio, Romolo, Gabriella, Gabriela, Didaco, Attilia, tiberio'),
(24, 4, 'Fedele'),
(24, 5, 'Amalia, Maria Ausiliatrice'),
(24, 6, 'Romolo, Gabriele, Battista, Giovanni, Giovanna, Zaira, Vanna, Vanni'),
(24, 7, 'Anita, Cristina'),
(24, 8, 'Bartolomeo, Michela, Anita, Bartolo, Dario, Daria'),
(24, 9, 'Pacifico, Mercedes'),
(24, 10, 'Luigi, Antonio, Raffaele'),
(24, 11, 'Flora'),
(24, 12, 'Irma, Adele, Adelaide'),
(25, 1, 'Savina, Savino, Sabino, Sabina'),
(25, 2, 'Costanza, Romeo'),
(25, 3, 'Annunziata, Nunzia, Nunzio'),
(25, 4, 'Franca, Franco, Marco'),
(25, 5, 'Gregorio, Beda, Adelmo'),
(25, 6, 'Orio, Oriella, Orietta, Oride, Oriana, Prospero, Prospera'),
(25, 7, 'Giacomo, Tea, Ivo, Iva, Ivonne, Ivette, Giacomo, Giacoma, Cristoforo'),
(25, 8, 'Erminia, Luigi, Patrizia, Patricia, Patti, Patty, Ludovico, Ludovica'),
(25, 9, 'Aurelia, Frido, Sergio, Aurelio'),
(25, 10, 'Daria, Dario, Gaudenzio, Gaudenzia'),
(25, 11, 'Caterina, Gioconda'),
(25, 12, 'Christel, Eugenia'),
(26, 1, 'Tito e Timoteo, Paola'),
(26, 2, 'Nestore,'),
(26, 3, 'Eginardo, Emanuele, Manuel, Quadrato, Emanuela'),
(26, 4, 'Alida, Marcellino, Bianca'),
(26, 5, 'Filippo'),
(26, 6, 'Rodolfo, Elisa, Filippo, Filippa, Vigilio, Vigilia'),
(26, 7, 'Anna, Camilla, Gioacchino, Rosanna'),
(26, 8, 'Alessandro'),
(26, 9, 'Cosma, Damiano, Nilo, Cosimo, Cosima'),
(26, 10, 'Evaristo'),
(26, 11, 'Liberale, Delfina'),
(26, 12, 'Stefano'),
(27, 1, 'Angela , Elvira'),
(27, 2, 'Onorina'),
(27, 3, 'Augusta, Ruperto, Romolo, Oliviero, Zita'),
(27, 4, 'Zita'),
(27, 5, 'Federico, Oliviero, Agostino'),
(27, 6, 'Cirillo, Lelio, Tosco, Tosca'),
(27, 7, 'Asja, Celestino, Natalia, Natalina, Natascia, Celeste'),
(27, 8, 'Monica, Monika'),
(27, 9, 'Vincenzo, Vincenza, Cenzo, Cenza, Damiano, Damiana'),
(27, 10, 'Fiorenzo, Delia'),
(27, 11, 'Astrid, Virgilio, Gustavo, Adelmo'),
(27, 12, 'Fabiola, Giovanni (evangelista), Delfina'),
(28, 1, 'Tommaso, Manfredi'),
(28, 2, 'Le sacre ceneri, Antonietta, Erminia, Erminio, Romano, teresio'),
(28, 3, 'Sisto'),
(28, 4, 'Valeria, Manlio'),
(28, 5, 'Emilio, Priamo, Emilia'),
(28, 6, 'Ireneo, Attilio'),
(28, 7, 'Nazario'),
(28, 8, 'Agostino, Viviano, Viviana, Agostina'),
(28, 9, 'Venceslao'),
(28, 10, 'Simona, Simone, Simeone, Simeona, Simonella, Simonetta, Giuda'),
(28, 11, 'Giacomo'),
(28, 12, 'Iolanda, Dorma, Donna'),
(29, 1, 'Gilda, Gildo, Ciro, Costanzo, Sabrina'),
(29, 2, 'Giusto'),
(29, 3, 'Secondo'),
(29, 4, 'Antonia, Karen, Caterina, Gomberto'),
(29, 5, 'Massimino, Ademaro, Massimo'),
(29, 6, 'Pietro, Paolo, Paola, Piera, Piero, Pierina, Pieruccia'),
(29, 7, 'Beatrice, Marta, Lucilla'),
(29, 8, 'Martirio, Sabina, Sabino, Savina, Savino'),
(29, 9, 'Gabriele, Michele, Raffaele, Michela, Michelina, Lina, Lino, Micaela'),
(29, 10, 'Ermelinda, Michele, Massimiliano'),
(29, 11, 'Saturnino'),
(29, 12, 'Tommaso, Pietro, Pietra, Ursino, Davide'),
(30, 1, 'Giovanni, Martina, Serenella'),
(30, 3, 'Amedeo, Zosimo'),
(30, 4, 'Pio, Lodovica, Lodovico, Sofia, Sonia, Rosamunda'),
(30, 5, 'Giovanni, Ferdinando'),
(30, 6, 'Protomartiri Romani, Ernesto'),
(30, 7, 'Donatella, Pietro'),
(30, 8, 'Bonomio, Rosa'),
(30, 9, 'Gerolamo, Rachele, Sofia, Sonia, Sonya, Geronimo, Girolamo'),
(30, 10, 'Benvenuta, Lucano, Quintino'),
(30, 11, 'Andrea'),
(30, 12, 'Eugenio, Liberio, Libero, Libera, Eugenia'),
(31, 1, 'Giovanni Bosco, Marcella, Lodovico, Lodovica, Geminiano, Nico'),
(31, 3, 'Beniamino'),
(31, 5, 'Angela, Giovanna d''Arco, Petronilla'),
(31, 7, 'Ignazio, Fabio'),
(31, 8, 'Aidano, Aida, Aristide'),
(31, 10, 'Volfando di Ratisbona, Angelo D”Acri'),
(31, 12, 'Donata, Silvestro, Fiore, Fiorella, Fiorello, Sesto, Melania');

ALTER TABLE `santi`
  ADD PRIMARY KEY (`giorno`,`mese`);
